export const proxyAiVoicemailOutputs = [
  {
    voicemailId: "VM-1042",
    modelName: "prototype-voicemail-proxy",
    reason: "Chest pain and shortness of breath overnight.",
    reasonConfidence: "High",
    summary: "Caller reports chest pain with trouble breathing and asked for an urgent callback.",
    summaryConfidence: "High",
    nextStep: "Immediate callback + advise emergency care",
    nextStepConfidence: "High",
    urgencyFallback: "Critical",
  },
  {
    voicemailId: "VM-1043",
    modelName: "prototype-voicemail-proxy",
    reason: "Repeat call reporting worsening chest tightness.",
    reasonConfidence: "High",
    summary: "Called back 14 minutes later saying symptoms are worse and asking if someone is there yet.",
    summaryConfidence: "High",
    nextStep: "Immediate callback + advise emergency care",
    nextStepConfidence: "High",
    urgencyFallback: "Critical",
  },
  {
    voicemailId: "VM-1041",
    modelName: "prototype-voicemail-proxy",
    reason: "Rash after starting antibiotics.",
    reasonConfidence: "Medium",
    summary: "Started antibiotics yesterday and now has a spreading rash. Wants advice today.",
    summaryConfidence: "Medium",
    nextStep: "Nurse callback this morning",
    nextStepConfidence: "Medium",
    urgencyFallback: "High",
  },
  {
    voicemailId: "VM-1040",
    modelName: "prototype-voicemail-proxy",
    reason: "Repeat call noting rash is spreading to chest.",
    reasonConfidence: "High",
    summary: "Follow-up voicemail adds that the rash is spreading and the patient is unsure whether to take the next antibiotic dose.",
    summaryConfidence: "High",
    nextStep: "Nurse callback this morning",
    nextStepConfidence: "High",
    urgencyFallback: "High",
  },
  {
    voicemailId: "VM-1038",
    modelName: "prototype-voicemail-proxy",
    reason: "Child has high fever and parent requests same-day visit.",
    reasonConfidence: "Medium",
    summary: "Parent called asking for the earliest appointment today due to a child's fever overnight.",
    summaryConfidence: "Medium",
    nextStep: "Offer same-day GP slot",
    nextStepConfidence: "Medium",
    urgencyFallback: "High",
  },
  {
    voicemailId: "VM-1036",
    modelName: "prototype-voicemail-proxy",
    reason: "Parent requests urgent review for infant with fever overnight.",
    reasonConfidence: "High",
    summary: "Caller says her infant developed a fever overnight and asks for the earliest urgent appointment today.",
    summaryConfidence: "High",
    nextStep: "Offer same-day GP slot",
    nextStepConfidence: "High",
    urgencyFallback: "Normal",
  },
  {
    voicemailId: "VM-1037",
    modelName: "prototype-voicemail-proxy",
    reason: "Repeat inhaler prescription requested.",
    reasonConfidence: "High",
    summary: "Requests repeat script for asthma inhaler before running out tomorrow.",
    summaryConfidence: "High",
    nextStep: "Send to GP prescription queue",
    nextStepConfidence: "High",
    urgencyFallback: "Normal",
  },
  {
    voicemailId: "VM-1035",
    modelName: "prototype-voicemail-proxy",
    reason: "Wants to discuss blood pressure medication with GP.",
    reasonConfidence: "Medium",
    summary: "Asked specifically for Dr Lee to call back regarding side effects from blood pressure medication.",
    summaryConfidence: "Medium",
    nextStep: "Add to doctor callback list",
    nextStepConfidence: "Medium",
    urgencyFallback: "Normal",
  },
  {
    voicemailId: "VM-1032",
    modelName: "prototype-voicemail-proxy",
    reason: "Medical certificate request for work.",
    reasonConfidence: "High",
    summary: "Requested a work certificate for illness earlier this week.",
    summaryConfidence: "High",
    nextStep: "Prepare certificate request",
    nextStepConfidence: "High",
    urgencyFallback: "Low",
  },
  {
    voicemailId: "VM-1030",
    modelName: "prototype-voicemail-proxy",
    reason: "Callback requested with unclear purpose.",
    reasonConfidence: "Low",
    summary: "Left a short callback request without identifying information or reason for contact.",
    summaryConfidence: "Low",
    nextStep: "Review transcript and return call",
    nextStepConfidence: "Low",
    urgencyFallback: "Unknown",
  },
  {
    voicemailId: "VM-1028",
    modelName: "prototype-voicemail-proxy",
    reason: "Following up on blood test results.",
    reasonConfidence: "High",
    summary: "Patient asking whether last week's blood test results are back and if a callback is needed.",
    summaryConfidence: "High",
    nextStep: "Nurse review results before callback",
    nextStepConfidence: "High",
    urgencyFallback: "Normal",
  },
  {
    voicemailId: "VM-1027",
    modelName: "prototype-voicemail-proxy",
    reason: "Second voicemail asking whether fasting results need urgent review.",
    reasonConfidence: "Medium",
    summary: "Called again to say she missed a prior callback and wants to know if anything urgent was found in the test results.",
    summaryConfidence: "Medium",
    nextStep: "Nurse review results before callback",
    nextStepConfidence: "Medium",
    urgencyFallback: "Normal",
  },
];

export const voicemailIntentClassifications = [
  { voicemailId: "VM-1042", intentId: 1, classificationScore: 0.97 },
  { voicemailId: "VM-1042", intentId: 3, classificationScore: 0.66 },
  { voicemailId: "VM-1042", intentId: 7, classificationScore: 0.48 },
  { voicemailId: "VM-1043", intentId: 1, classificationScore: 0.98 },
  { voicemailId: "VM-1043", intentId: 3, classificationScore: 0.71 },
  { voicemailId: "VM-1043", intentId: 7, classificationScore: 0.4 },
  { voicemailId: "VM-1041", intentId: 2, classificationScore: 0.95 },
  { voicemailId: "VM-1041", intentId: 1, classificationScore: 0.67 },
  { voicemailId: "VM-1041", intentId: 7, classificationScore: 0.32 },
  { voicemailId: "VM-1040", intentId: 2, classificationScore: 0.96 },
  { voicemailId: "VM-1040", intentId: 1, classificationScore: 0.71 },
  { voicemailId: "VM-1040", intentId: 3, classificationScore: 0.41 },
  { voicemailId: "VM-1038", intentId: 4, classificationScore: 0.93 },
  { voicemailId: "VM-1038", intentId: 1, classificationScore: 0.78 },
  { voicemailId: "VM-1038", intentId: 7, classificationScore: 0.34 },
  { voicemailId: "VM-1036", intentId: 4, classificationScore: 0.88 },
  { voicemailId: "VM-1036", intentId: 1, classificationScore: 0.82 },
  { voicemailId: "VM-1036", intentId: 7, classificationScore: 0.28 },
  { voicemailId: "VM-1037", intentId: 5, classificationScore: 0.96 },
  { voicemailId: "VM-1037", intentId: 8, classificationScore: 0.62 },
  { voicemailId: "VM-1037", intentId: 7, classificationScore: 0.29 },
  { voicemailId: "VM-1035", intentId: 3, classificationScore: 0.91 },
  { voicemailId: "VM-1035", intentId: 2, classificationScore: 0.74 },
  { voicemailId: "VM-1035", intentId: 1, classificationScore: 0.58 },
  { voicemailId: "VM-1032", intentId: 8, classificationScore: 0.94 },
  { voicemailId: "VM-1032", intentId: 7, classificationScore: 0.65 },
  { voicemailId: "VM-1030", intentId: 7, classificationScore: 0.62 },
  { voicemailId: "VM-1030", intentId: 8, classificationScore: 0.43 },
  { voicemailId: "VM-1028", intentId: 6, classificationScore: 0.95 },
  { voicemailId: "VM-1028", intentId: 7, classificationScore: 0.61 },
  { voicemailId: "VM-1027", intentId: 6, classificationScore: 0.89 },
  { voicemailId: "VM-1027", intentId: 3, classificationScore: 0.64 },
  { voicemailId: "VM-1027", intentId: 7, classificationScore: 0.37 },
];
