export const initialVoicemails = [
  {
    id: "VM-1042",
    patient: "Mark Davis",
    location: "Harbour Central",
    phone: "021 555 018",
    time: "7:12 AM",
    age: "42m ago",
    intent: "Symptom concern",
    urgency: "Critical",
    queue: "Emergency Review",
    owner: "Nurse triage",
    status: "New",
    confidence: "High",
    reason: "Chest pain and shortness of breath overnight.",
    summary: "Caller reports chest pain with trouble breathing and asked for an urgent callback.",
    nextStep: "Immediate callback + advise emergency care",
    transcript:
      "Hi, this is Mark Davis. I've had chest pain since this morning and I'm a bit short of breath. Please call me back as soon as possible.",
  },
  {
    id: "VM-1041",
    patient: "Sarah Thompson",
    location: "Sunset West",
    phone: "027 555 223",
    time: "6:55 AM",
    age: "59m ago",
    intent: "Medication reaction",
    urgency: "High",
    queue: "Clinical Triage",
    owner: "Nurse triage",
    status: "New",
    confidence: "High",
    reason: "Rash after starting antibiotics.",
    summary: "Started antibiotics yesterday and now has a spreading rash. Wants advice today.",
    nextStep: "Nurse callback this morning",
    transcript:
      "Hello, I started antibiotics yesterday and woke up with a rash on my arms. Could someone let me know if I should keep taking them?",
  },
  {
    id: "VM-1038",
    patient: "Noah Patel",
    location: "Harbour South",
    phone: "022 555 401",
    time: "6:40 AM",
    age: "1h 14m ago",
    intent: "Appointment request",
    urgency: "High",
    queue: "Same-Day Appointments",
    owner: "Front desk",
    status: "In Progress",
    confidence: "Medium",
    reason: "Child has high fever and parent requests same-day visit.",
    summary: "Parent called asking for the earliest appointment today due to a child's fever overnight.",
    nextStep: "Offer same-day GP slot",
    transcript: "Hi, my son has had a high fever since last night. We'd like to get him seen today if possible.",
  },
  {
    id: "VM-1037",
    patient: "Emily Chen",
    location: "Harbour Central",
    phone: "021 555 772",
    time: "6:22 AM",
    age: "1h 32m ago",
    intent: "Prescription request",
    urgency: "Normal",
    queue: "Prescription Requests",
    owner: "GP review",
    status: "New",
    confidence: "High",
    reason: "Repeat inhaler prescription requested.",
    summary: "Requests repeat script for asthma inhaler before running out tomorrow.",
    nextStep: "Send to GP prescription queue",
    transcript:
      "Hi, I need a repeat prescription for my asthma inhaler. I'm nearly out and would appreciate it being sent through today.",
  },
  {
    id: "VM-1035",
    patient: "James Wilson",
    location: "Sunset West",
    phone: "020 555 119",
    time: "5:58 AM",
    age: "1h 56m ago",
    intent: "Doctor callback",
    urgency: "Normal",
    queue: "GP Callbacks",
    owner: "Dr Lee",
    status: "New",
    confidence: "Medium",
    reason: "Wants to discuss blood pressure medication with GP.",
    summary: "Asked specifically for Dr Lee to call back regarding side effects from blood pressure medication.",
    nextStep: "Add to doctor callback list",
    transcript:
      "Could Dr Lee please call me today? I have a question about my blood pressure tablets and some dizziness.",
  },
  {
    id: "VM-1032",
    patient: "Olivia Brown",
    location: "Harbour South",
    phone: "021 555 642",
    time: "5:31 AM",
    age: "2h 23m ago",
    intent: "Administrative request",
    urgency: "Low",
    queue: "Admin Requests",
    owner: "Front desk",
    status: "Resolved",
    confidence: "High",
    reason: "Medical certificate request for work.",
    summary: "Requested a work certificate for illness earlier this week.",
    nextStep: "Prepare certificate request",
    transcript: "Hi, could I please get a medical certificate for work for the last two days?",
  },
  {
    id: "VM-1030",
    patient: "Unknown caller",
    location: "Harbour Central",
    phone: "09 555 9102",
    time: "4:44 AM",
    age: "3h 10m ago",
    intent: "General callback",
    urgency: "Unknown",
    queue: "Needs Review",
    owner: "Front desk",
    status: "New",
    confidence: "Low",
    reason: "Callback requested with unclear purpose.",
    summary: "Left a short callback request without identifying information or reason for contact.",
    nextStep: "Review transcript and return call",
    transcript: "Hi, can someone call me back this morning? Thanks.",
  },
  {
    id: "VM-1028",
    patient: "Ava Singh",
    location: "Sunset West",
    phone: "027 555 937",
    time: "4:09 AM",
    age: "3h 45m ago",
    intent: "Test results query",
    urgency: "Normal",
    queue: "Test Results",
    owner: "Nurse triage",
    status: "New",
    confidence: "High",
    reason: "Following up on blood test results.",
    summary: "Patient asking whether last week's blood test results are back and if a callback is needed.",
    nextStep: "Nurse review results before callback",
    transcript: "I had blood tests done last week and wanted to check whether the results are back yet.",
  },
];
