export const demoReferenceTime = "2026-03-10T08:02:00";

export const clinics = [
  { id: 1, name: "Harbour Central" },
  { id: 2, name: "Harbour South" },
  { id: 3, name: "Sunset West" },
];

export const gps = [
  { id: 1, name: "Dr Priya Nair", clinicId: 1, specialty: "Family medicine" },
  { id: 2, name: "Dr Aria Chen", clinicId: 2, specialty: "Family medicine" },
  { id: 3, name: "Dr Lee", clinicId: 3, specialty: "Family medicine" },
  { id: 4, name: "Dr Hannah Cole", clinicId: 3, specialty: "Women's health" },
  { id: 5, name: "Dr Mason Reid", clinicId: 1, specialty: "Respiratory medicine" },
];

export const patients = [
  { id: 1, fullName: "Mark Davis", phone: "021 555 018", clinicId: 1 },
  { id: 2, fullName: "Sarah Thompson", phone: "027 555 223", clinicId: 3 },
  { id: 3, fullName: "Noah Patel", phone: "022 555 401", clinicId: 2 },
  { id: 4, fullName: "Emily Chen", phone: "021 555 772", clinicId: 1 },
  { id: 5, fullName: "James Wilson", phone: "020 555 119", clinicId: 3 },
  { id: 6, fullName: "Olivia Brown", phone: "021 555 642", clinicId: 2 },
  { id: 7, fullName: "Ava Singh", phone: "027 555 937", clinicId: 3 },
  { id: 8, fullName: "Mia Carter", phone: "029 555 884", clinicId: 2 },
];

export const patientGpRelationships = [
  { patientId: 1, gpId: 1, relationshipType: "primary", isPrimary: 1 },
  { patientId: 1, gpId: 5, relationshipType: "care_team", isPrimary: 0 },
  { patientId: 2, gpId: 3, relationshipType: "primary", isPrimary: 1 },
  { patientId: 3, gpId: 2, relationshipType: "primary", isPrimary: 1 },
  { patientId: 4, gpId: 1, relationshipType: "primary", isPrimary: 1 },
  { patientId: 5, gpId: 3, relationshipType: "primary", isPrimary: 1 },
  { patientId: 6, gpId: 2, relationshipType: "primary", isPrimary: 1 },
  { patientId: 7, gpId: 4, relationshipType: "primary", isPrimary: 1 },
  { patientId: 8, gpId: 2, relationshipType: "primary", isPrimary: 1 },
  { patientId: 7, gpId: 3, relationshipType: "covering", isPrimary: 0 },
];

export const queues = [
  { id: 1, name: "Emergency Review", clinicId: null, isSystem: 1, defaultOwnerLabel: "Nurse triage" },
  { id: 2, name: "Clinical Triage", clinicId: null, isSystem: 1, defaultOwnerLabel: "Nurse triage" },
  { id: 3, name: "Same-Day Appointments", clinicId: null, isSystem: 1, defaultOwnerLabel: "Front desk" },
  { id: 4, name: "Prescription Requests", clinicId: null, isSystem: 1, defaultOwnerLabel: "GP review" },
  { id: 5, name: "GP Callbacks", clinicId: null, isSystem: 1, defaultOwnerLabel: "Front desk" },
  { id: 6, name: "Admin Requests", clinicId: null, isSystem: 1, defaultOwnerLabel: "Front desk" },
  { id: 7, name: "Needs Review", clinicId: null, isSystem: 1, defaultOwnerLabel: "Front desk" },
  { id: 8, name: "Test Results", clinicId: null, isSystem: 1, defaultOwnerLabel: "Nurse triage" },
  { id: 9, name: "Referral Coordination", clinicId: 3, isSystem: 0, defaultOwnerLabel: "Front desk" },
];

export const intents = [
  { id: 1, label: "Symptom concern", clinicId: null, isSystem: 1 },
  { id: 2, label: "Medication reaction", clinicId: null, isSystem: 1 },
  { id: 3, label: "Doctor callback", clinicId: null, isSystem: 1 },
  { id: 4, label: "Appointment request", clinicId: null, isSystem: 1 },
  { id: 5, label: "Prescription request", clinicId: null, isSystem: 1 },
  { id: 6, label: "Test results query", clinicId: null, isSystem: 1 },
  { id: 7, label: "General callback", clinicId: null, isSystem: 1 },
  { id: 8, label: "Administrative request", clinicId: null, isSystem: 1 },
  { id: 9, label: "Referral follow-up", clinicId: 3, isSystem: 0 },
];

export const intentQueueRoutes = [
  { clinicId: 1, intentId: 1, queueId: 1 },
  { clinicId: 1, intentId: 2, queueId: 2 },
  { clinicId: 1, intentId: 3, queueId: 5 },
  { clinicId: 1, intentId: 4, queueId: 3 },
  { clinicId: 1, intentId: 5, queueId: 4 },
  { clinicId: 1, intentId: 6, queueId: 8 },
  { clinicId: 1, intentId: 7, queueId: 7 },
  { clinicId: 1, intentId: 8, queueId: 6 },
  { clinicId: 2, intentId: 1, queueId: 1 },
  { clinicId: 2, intentId: 2, queueId: 2 },
  { clinicId: 2, intentId: 3, queueId: 5 },
  { clinicId: 2, intentId: 4, queueId: 3 },
  { clinicId: 2, intentId: 5, queueId: 4 },
  { clinicId: 2, intentId: 6, queueId: 8 },
  { clinicId: 2, intentId: 7, queueId: 7 },
  { clinicId: 2, intentId: 8, queueId: 6 },
  { clinicId: 3, intentId: 1, queueId: 1 },
  { clinicId: 3, intentId: 2, queueId: 2 },
  { clinicId: 3, intentId: 3, queueId: 5 },
  { clinicId: 3, intentId: 4, queueId: 3 },
  { clinicId: 3, intentId: 5, queueId: 4 },
  { clinicId: 3, intentId: 6, queueId: 8 },
  { clinicId: 3, intentId: 7, queueId: 7 },
  { clinicId: 3, intentId: 8, queueId: 6 },
];

export const urgencyKeywords = [
  { id: 1, clinicId: null, urgency: "Critical", keyword: "chest pain", isSystem: 1 },
  { id: 2, clinicId: null, urgency: "Critical", keyword: "short of breath", isSystem: 1 },
  { id: 3, clinicId: null, urgency: "Critical", keyword: "light-headed", isSystem: 1 },
  { id: 4, clinicId: null, urgency: "High", keyword: "rash", isSystem: 1 },
  { id: 5, clinicId: null, urgency: "High", keyword: "high fever", isSystem: 1 },
  { id: 6, clinicId: null, urgency: "High", keyword: "worse", isSystem: 1 },
  { id: 7, clinicId: null, urgency: "Normal", keyword: "prescription", isSystem: 1 },
  { id: 8, clinicId: null, urgency: "Normal", keyword: "test results", isSystem: 1 },
  { id: 9, clinicId: null, urgency: "Low", keyword: "medical certificate", isSystem: 1 },
  { id: 10, clinicId: 1, urgency: "Critical", keyword: "trouble breathing", isSystem: 0 },
  { id: 11, clinicId: 3, urgency: "High", keyword: "spreading", isSystem: 0 },
  { id: 12, clinicId: 2, urgency: "High", keyword: "same day", isSystem: 0 },
  { id: 13, clinicId: 2, urgency: "High", keyword: "infant", isSystem: 0 },
];

export const patientUrgencyMarkers = [
  {
    id: 1,
    patientId: 5,
    gpId: 3,
    urgency: "High",
    note: "Escalate any callback requests because of recent medication side effects and unstable blood pressure.",
    isActive: 1,
  },
  {
    id: 2,
    patientId: 8,
    gpId: 2,
    urgency: "Critical",
    note: "Infant with recent hospital presentation.",
    isActive: 1,
  }
];

export const voicemails = [
  {
    id: "VM-1042",
    patientId: 1,
    callerName: null,
    callerPhone: "021 555 018",
    clinicId: 1,
    queueId: 1,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T07:12:00",
    urgency: "Critical",
    status: "New",
    summaryConfidence: "High",
    reason: "Chest pain and shortness of breath overnight.",
    summary: "Caller reports chest pain with trouble breathing and asked for an urgent callback.",
    nextStep: "Immediate callback + advise emergency care",
    transcript: "Hi, this is Mark Davis. I've had chest pain since this morning and I'm a bit short of breath. Please call me back as soon as possible.",
    resolution_note: "They have called 111 and got admitted to hospital",
  },
  {
    id: "VM-1043",
    patientId: 1,
    callerName: null,
    callerPhone: "021 555 018",
    clinicId: 1,
    queueId: 1,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T07:26:00",
    urgency: "Critical",
    status: "New",
    summaryConfidence: "High",
    reason: "Repeat call reporting worsening chest tightness.",
    summary: "Called back 14 minutes later saying symptoms are worse and asking if someone is there yet.",
    nextStep: "Immediate callback + advise emergency care",
    transcript: "It's Mark Davis again. The chest tightness is worse now and I'm starting to feel light-headed. Please call me back urgently.",
    resolution_note: "They have called 111 and got admitted to hospital",
  },
  {
    id: "VM-1041",
    patientId: 2,
    callerName: null,
    callerPhone: "027 555 223",
    clinicId: 3,
    queueId: 2,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T06:55:00",
    urgency: "High",
    status: "New",
    summaryConfidence: "Medium",
    reason: "Rash after starting antibiotics.",
    summary: "Started antibiotics yesterday and now has a spreading rash. Wants advice today.",
    nextStep: "Nurse callback this morning",
    transcript: "Hello, I started antibiotics yesterday and woke up with a rash on my arms. Could someone let me know if I should keep taking them?",
    resolution_note: null,
  },
  {
    id: "VM-1040",
    patientId: 2,
    callerName: null,
    callerPhone: "027 555 223",
    clinicId: 3,
    queueId: 2,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T07:03:00",
    urgency: "High",
    status: "New",
    summaryConfidence: "High",
    reason: "Repeat call noting rash is spreading to chest.",
    summary: "Follow-up voicemail adds that the rash is spreading and the patient is unsure whether to take the next antibiotic dose.",
    nextStep: "Nurse callback this morning",
    transcript: "Hi, it's Sarah Thompson again. The rash is spreading onto my chest now and I don't know if I should take the next tablet.",
    resolution_note: null,
  },
  {
    id: "VM-1038",
    patientId: 3,
    callerName: null,
    callerPhone: "022 555 401",
    clinicId: 2,
    queueId: 3,
    assignedGpId: null,
    ownerLabel: "Front desk",
    receivedAt: "2026-03-10T06:40:00",
    urgency: "High",
    status: "In Progress",
    summaryConfidence: "Medium",
    reason: "Child has high fever and parent requests same-day visit.",
    summary: "Parent called asking for the earliest appointment today due to a child's fever overnight.",
    nextStep: "Offer same-day GP slot",
    transcript: "Hi, my son has had a high fever since last night. We'd like to get him seen today if possible.",
    resolution_note: null,  
  },
  {
    id: "VM-1036",
    patientId: 8,
    callerName: null,
    callerPhone: "029 555 884",
    clinicId: 2,
    queueId: 3,
    assignedGpId: null,
    ownerLabel: "Front desk",
    receivedAt: "2026-03-10T06:12:00",
    urgency: "Normal",
    status: "New",
    summaryConfidence: "High",
    reason: "Parent requests urgent review for infant with fever overnight.",
    summary: "Caller says her infant developed a fever overnight and asks for the earliest urgent appointment today.",
    nextStep: "Offer same-day GP slot",
    transcript: "Hi, this is Mia Carter. My infant has had a fever since the middle of the night and I want to know if she needs to be seen this morning.",
    resolution_note: "Called patient back and booked same-day review.",
  },
  {
    id: "VM-1037",
    patientId: 4,
    callerName: null,
    callerPhone: "021 555 772",
    clinicId: 1,
    queueId: 4,
    assignedGpId: null,
    ownerLabel: "GP review",
    receivedAt: "2026-03-10T06:22:00",
    urgency: "Normal",
    status: "New",
    summaryConfidence: "High",
    reason: "Repeat inhaler prescription requested.",
    summary: "Requests repeat script for asthma inhaler before running out tomorrow.",
    nextStep: "Send to GP prescription queue",
    transcript: "Hi, I need a repeat prescription for my asthma inhaler. I'm nearly out and would appreciate it being sent through today.",
    resolution_note: null,  
  },
  {
    id: "VM-1035",
    patientId: 5,
    callerName: null,
    callerPhone: "020 555 119",
    clinicId: 3,
    queueId: 5,
    assignedGpId: 3,
    ownerLabel: "Dr Lee",
    receivedAt: "2026-03-10T05:58:00",
    urgency: "Normal",
    status: "New",
    summaryConfidence: "Medium",
    reason: "Wants to discuss blood pressure medication with GP.",
    summary: "Asked specifically for Dr Lee to call back regarding side effects from blood pressure medication.",
    nextStep: "Add to doctor callback list",
    transcript: "Could Dr Lee please call me today? I have a question about my blood pressure tablets and some dizziness.",
    resolution_note: null,  
  },
  {
    id: "VM-1032",
    patientId: 6,
    callerName: null,
    callerPhone: "021 555 642",
    clinicId: 2,
    queueId: 6,
    assignedGpId: null,
    ownerLabel: "Front desk",
    receivedAt: "2026-03-10T05:31:00",
    urgency: "Low",
    status: "Resolved",
    summaryConfidence: "High",
    reason: "Medical certificate request for work.",
    summary: "Requested a work certificate for illness earlier this week.",
    nextStep: "Prepare certificate request",
    transcript: "Hi, could I please get a medical certificate for work for the last two days?",
    resolution_note: null,  
  },
  {
    id: "VM-1030",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 9102",
    clinicId: 1,
    queueId: 7,
    assignedGpId: null,
    ownerLabel: "Front desk",
    receivedAt: "2026-03-10T04:44:00",
    urgency: "Unknown",
    status: "New",
    summaryConfidence: "Low",
    reason: "Callback requested with unclear purpose.",
    summary: "Left a short callback request without identifying information or reason for contact.",
    nextStep: "Review transcript and return call",
    transcript: "Hi, can someone call me back this morning? Thanks.",
    resolution_note: null,  
  },
  {
    id: "VM-1028",
    patientId: 7,
    callerName: null,
    callerPhone: "027 555 937",
    clinicId: 3,
    queueId: 8,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T04:09:00",
    urgency: "Normal",
    status: "New",
    summaryConfidence: "High",
    reason: "Following up on blood test results.",
    summary: "Patient asking whether last week's blood test results are back and if a callback is needed.",
    nextStep: "Nurse review results before callback",
    transcript: "I had blood tests done last week and wanted to check whether the results are back yet.",
    resolution_note: null,  
  },
  {
    id: "VM-1027",
    patientId: 7,
    callerName: null,
    callerPhone: "027 555 937",
    clinicId: 3,
    queueId: 8,
    assignedGpId: null,
    ownerLabel: "Nurse triage",
    receivedAt: "2026-03-10T04:21:00",
    urgency: "Normal",
    status: "New",
    summaryConfidence: "Medium",
    reason: "Second voicemail asking whether fasting results need urgent review.",
    summary: "Called again to say she missed a prior callback and wants to know if anything urgent was found in the test results.",
    nextStep: "Nurse review results before callback",
    transcript: "Hello, it's Ava Singh again. I just wanted to check whether the blood test showed anything urgent because I may have missed your call yesterday.",
    resolution_note: null,  
  },
];

export const voicemailIntentClassifications = [
  { voicemailId: "VM-1042", intentId: 1, classificationScore: 0.97 },
  { voicemailId: "VM-1042", intentId: 3, classificationScore: 0.66 },
  { voicemailId: "VM-1042", intentId: 7, classificationScore: 0.48 },
  { voicemailId: "VM-1043", intentId: 1, classificationScore: 0.98 },
  { voicemailId: "VM-1043", intentId: 3, classificationScore: 0.71 },
  { voicemailId: "VM-1043", intentId: 7, classificationScore: 0.4 },
  { voicemailId: "VM-1041", intentId: 2, classificationScore: 0.95 },
  { voicemailId: "VM-1041", intentId: 1, classificationScore: 0.67 },
  { voicemailId: "VM-1041", intentId: 7, classificationScore: 0.32 },
  { voicemailId: "VM-1040", intentId: 2, classificationScore: 0.96 },
  { voicemailId: "VM-1040", intentId: 1, classificationScore: 0.71 },
  { voicemailId: "VM-1040", intentId: 3, classificationScore: 0.41 },
  { voicemailId: "VM-1038", intentId: 4, classificationScore: 0.93 },
  { voicemailId: "VM-1038", intentId: 1, classificationScore: 0.78 },
  { voicemailId: "VM-1038", intentId: 7, classificationScore: 0.34 },
  { voicemailId: "VM-1036", intentId: 4, classificationScore: 0.88 },
  { voicemailId: "VM-1036", intentId: 1, classificationScore: 0.82 },
  { voicemailId: "VM-1036", intentId: 7, classificationScore: 0.28 },
  { voicemailId: "VM-1037", intentId: 5, classificationScore: 0.96 },
  { voicemailId: "VM-1037", intentId: 8, classificationScore: 0.62 },
  { voicemailId: "VM-1037", intentId: 7, classificationScore: 0.29 },
  { voicemailId: "VM-1035", intentId: 3, classificationScore: 0.91 },
  { voicemailId: "VM-1035", intentId: 2, classificationScore: 0.74 },
  { voicemailId: "VM-1035", intentId: 1, classificationScore: 0.58 },
  { voicemailId: "VM-1032", intentId: 8, classificationScore: 0.94 },
  { voicemailId: "VM-1032", intentId: 7, classificationScore: 0.65 },
  { voicemailId: "VM-1030", intentId: 7, classificationScore: 0.62 },
  { voicemailId: "VM-1030", intentId: 8, classificationScore: 0.43 },
  { voicemailId: "VM-1028", intentId: 6, classificationScore: 0.95 },
  { voicemailId: "VM-1028", intentId: 7, classificationScore: 0.61 },
  { voicemailId: "VM-1027", intentId: 6, classificationScore: 0.89 },
  { voicemailId: "VM-1027", intentId: 3, classificationScore: 0.64 },
  { voicemailId: "VM-1027", intentId: 7, classificationScore: 0.37 },
];
