export const demoReferenceTime = "2026-03-10T08:02:00";

export const structuredVoicemails = [
  {
    voicemailId: "VM-1042",
    patientId: 1,
    callerName: null,
    callerPhone: "021 555 018",
    clinicId: 1,
    receivedAt: "2026-03-10T07:12:00",
    transcription: "Hi, this is Mark Davis. I've had chest pain since this morning and I'm a bit short of breath. Please call me back as soon as possible.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Caller reports chest pain with trouble breathing and asked for an urgent callback.",
    reasonForCall: "Chest pain and shortness of breath overnight.",
    recommendedSteps: "Immediate callback + advise emergency care",
  },
  {
    voicemailId: "VM-1043",
    patientId: 1,
    callerName: null,
    callerPhone: "021 555 018",
    clinicId: 1,
    receivedAt: "2026-03-10T07:26:00",
    transcription: "It's Mark Davis again. The chest tightness is worse now and I'm starting to feel light-headed. Please call me back urgently.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Called back 14 minutes later saying symptoms are worse and asking if someone is there yet.",
    reasonForCall: "Repeat call reporting worsening chest tightness.",
    recommendedSteps: "Immediate callback + advise emergency care",
  },
  {
    voicemailId: "VM-1041",
    patientId: 2,
    callerName: null,
    callerPhone: "027 555 223",
    clinicId: 3,
    receivedAt: "2026-03-10T06:55:00",
    transcription: "Hello, I started antibiotics yesterday and woke up with a rash on my arms. Could someone let me know if I should keep taking them?",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Started antibiotics yesterday and now has a spreading rash. Wants advice today.",
    reasonForCall: "Rash after starting antibiotics.",
    recommendedSteps: "Nurse callback this morning",
  },
  {
    voicemailId: "VM-1040",
    patientId: 2,
    callerName: null,
    callerPhone: "027 555 223",
    clinicId: 3,
    receivedAt: "2026-03-10T07:03:00",
    transcription: "Hi, it's Sarah Thompson again. The rash is spreading onto my chest now and I don't know if I should take the next tablet.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Follow-up voicemail adds that the rash is spreading and the patient is unsure whether to take the next antibiotic dose.",
    reasonForCall: "Repeat call noting rash is spreading to chest.",
    recommendedSteps: "Nurse callback this morning",
  },
  {
    voicemailId: "VM-1038",
    patientId: 3,
    callerName: null,
    callerPhone: "022 555 401",
    clinicId: 2,
    receivedAt: "2026-03-10T06:40:00",
    transcription: "Hi, my son has had a high fever since last night. We'd like to get him seen today if possible.",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Parent called asking for the earliest appointment today due to a child's fever overnight.",
    reasonForCall: "Child has high fever and parent requests same-day visit.",
    recommendedSteps: "Offer same-day GP slot",
  },
  {
    voicemailId: "VM-1036",
    patientId: 8,
    callerName: null,
    callerPhone: "029 555 884",
    clinicId: 2,
    receivedAt: "2026-03-10T06:12:00",
    transcription: "Hi, this is Mia Carter. My infant has had a fever since the middle of the night and I want to know if she needs to be seen this morning.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Caller says her infant developed a fever overnight and asks for the earliest urgent appointment today.",
    reasonForCall: "Parent requests urgent review for infant with fever overnight.",
    recommendedSteps: "Offer same-day GP slot",
  },
  {
    voicemailId: "VM-1037",
    patientId: 4,
    callerName: null,
    callerPhone: "021 555 772",
    clinicId: 1,
    receivedAt: "2026-03-10T06:22:00",
    transcription: "Hi, I need a repeat prescription for my asthma inhaler. I'm nearly out and would appreciate it being sent through today.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Requests repeat script for asthma inhaler before running out tomorrow.",
    reasonForCall: "Repeat inhaler prescription requested.",
    recommendedSteps: "Send to GP prescription queue",
  },
  {
    voicemailId: "VM-1046",
    patientId: 10,
    callerName: null,
    callerPhone: "022 555 612",
    clinicId: 2,
    receivedAt: "2026-03-10T06:18:00",
    transcription: "Hi uh this is Grace maybe, um the med... the blue one, I need it again and my... throd? feels off, call me, sorry, bad line.",
    transcriptionConfidence: "Low",
    transcriptionSummary: "Caller maybe needs medication and throat issue, line bad.",
    reasonForCall: "Unclear request due to poor transcription; possible medication and symptom concern.",
    recommendedSteps: "Play recording and confirm the caller's request before routing.",
  },
  {
    voicemailId: "VM-1045",
    patientId: 9,
    callerName: null,
    callerPhone: "021 555 993",
    clinicId: 1,
    receivedAt: "2026-03-10T06:16:00",
    transcription: "",
    transcriptionConfidence: "Low",
    transcriptionSummary: "",
    reasonForCall: "",
    recommendedSteps: "",
  },
  {
    voicemailId: "VM-1044",
    patientId: 5,
    callerName: null,
    callerPhone: "020 555 119",
    clinicId: 3,
    receivedAt: "2026-03-10T06:04:00",
    transcription: "",
    transcriptionConfidence: "Low",
    transcriptionSummary: "",
    reasonForCall: "",
    recommendedSteps: "",
  },
  {
    voicemailId: "VM-1035",
    patientId: 5,
    callerName: null,
    callerPhone: "020 555 119",
    clinicId: 3,
    receivedAt: "2026-03-10T05:58:00",
    transcription: "Could Dr Lee please call me today? I have a question about my blood pressure tablets and some dizziness.",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Asked specifically for Dr Lee to call back regarding side effects from blood pressure medication.",
    reasonForCall: "Wants to discuss blood pressure medication with GP.",
    recommendedSteps: "Add to doctor callback list",
  },
  {
    voicemailId: "VM-1032",
    patientId: 6,
    callerName: null,
    callerPhone: "021 555 642",
    clinicId: 2,
    receivedAt: "2026-03-10T05:31:00",
    transcription: "Hi, could I please get a medical certificate for work for the last two days?",
    transcriptionConfidence: "High",
    transcriptionSummary: "Requested a work certificate for illness earlier this week.",
    reasonForCall: "Medical certificate request for work.",
    recommendedSteps: "Prepare certificate request",
  },
  {
    voicemailId: "VM-1030",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 9102",
    clinicId: 1,
    receivedAt: "2026-03-10T04:44:00",
    transcription: "Hi, can someone call me back this morning? Thanks.",
    transcriptionConfidence: "Low",
    transcriptionSummary: "Left a short callback request without identifying information or reason for contact.",
    reasonForCall: "Callback requested with unclear purpose.",
    recommendedSteps: "Review transcript and return call",
  },
  {
    voicemailId: "VM-1026",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 8044",
    clinicId: 1,
    receivedAt: "2026-03-10T05:12:00",
    transcription: "Hi, I'm not in your system yet, but I've had chest pain for the last hour and now I'm getting short of breath. Please call me back urgently.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Unknown caller reports chest pain and worsening breathing symptoms and asks for an urgent callback.",
    reasonForCall: "Unknown caller with acute chest pain and shortness of breath.",
    recommendedSteps: "Immediate callback + advise emergency care",
  },
  {
    voicemailId: "VM-1025",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 8045",
    clinicId: 2,
    receivedAt: "2026-03-10T05:04:00",
    transcription: "Hello, my toddler has had a high fever since overnight and I'd like the earliest same day appointment. We're new to the clinic.",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Unknown caller requests the earliest same-day appointment for a toddler with a high fever.",
    reasonForCall: "Unknown caller requesting urgent same-day appointment for a child with fever.",
    recommendedSteps: "Offer same-day GP slot",
  },
  {
    voicemailId: "VM-1024",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 8046",
    clinicId: 1,
    receivedAt: "2026-03-10T04:52:00",
    transcription: "Hi, I need a repeat prescription for my eczema cream. I'm not one of your regular patients yet, but I only have a few days left.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Unknown caller asks for a repeat prescription and says they only have a few days of medication left.",
    reasonForCall: "Unknown caller requesting a repeat prescription.",
    recommendedSteps: "Send to GP prescription queue",
  },
  {
    voicemailId: "VM-1023",
    patientId: null,
    callerName: "Unknown caller",
    callerPhone: "09 555 8047",
    clinicId: 2,
    receivedAt: "2026-03-10T04:36:00",
    transcription: "Hello, I need a medical certificate for work for yesterday and today. I'm new to the clinic and wanted to see if someone can help.",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Unknown caller requests a work medical certificate for the previous two days.",
    reasonForCall: "Unknown caller requesting an administrative medical certificate.",
    recommendedSteps: "Prepare certificate request",
  },
  {
    voicemailId: "VM-1028",
    patientId: 7,
    callerName: null,
    callerPhone: "027 555 937",
    clinicId: 3,
    receivedAt: "2026-03-10T04:09:00",
    transcription: "I had blood tests done last week and wanted to check whether the results are back yet.",
    transcriptionConfidence: "High",
    transcriptionSummary: "Patient asking whether last week's blood test results are back and if a callback is needed.",
    reasonForCall: "Following up on blood test results.",
    recommendedSteps: "Nurse review results before callback",
  },
  {
    voicemailId: "VM-1027",
    patientId: 7,
    callerName: null,
    callerPhone: "027 555 937",
    clinicId: 3,
    receivedAt: "2026-03-10T04:21:00",
    transcription: "Hello, it's Ava Singh again. I just wanted to check whether the blood test showed anything urgent because I may have missed your call yesterday.",
    transcriptionConfidence: "Medium",
    transcriptionSummary: "Called again to say she missed a prior callback and wants to know if anything urgent was found in the test results.",
    reasonForCall: "Second voicemail asking whether fasting results need urgent review.",
    recommendedSteps: "Nurse review results before callback",
  },
];
